# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Build and Test

# This determines when this workflow is run
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        env:
          - CI_NAME: build-and-test-humble
            ROS_DISTRO: humble
          - CI_NAME: build-and-test-rolling
            ROS_DISTRO: rolling
          - CI_NAME: build-and-test-iron
            ROS_DISTRO: iron

    env:
      ROS_REPO: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Run industrial_ci
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
